#
[build-system]
requires      = ["setuptools", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[project]
name            = "dataset-tools"
description     = "An ultralight metadata viewer to help you visualize and edit dataset text."
authors         = [{ name = "Ktiseos Nyx", email = "Dataset-Tools@noreply.github.com" }]
requires-python = ">= 3.10"
license         = { file = "LICENSE" }
readme          = "README.md"
urls            = { source = "https://github.com/orgs/Ktiseos-Nyx/Dataset-Tools" }
dynamic         = ["version"]

keywords = [
    "training",
    "text",
    "images",
    "AI",
    "editing",
    "dataset",
    "metadata",
    "generative",
    "art",
]

dependencies = ["PyQt6", "rich", "pillow", "pydantic"]

[project.optional-dependencies]
dev = ["pytest"]

[project.scripts]
dataset-tools = "dataset_tools.main:main"

[tool.setuptools_scm]
write_to = "_version.py"

[tool.uv]
dev-dependencies = ["pytest"]
